groups:
- name: sap-hana-resource-monitoring
  rules:
  - alert: sap-hana-master-resource-down
    expr: absent(cluster_node_resources{resource_name="rsc_saphana_prd_hdb00",role="master"})
    labels:
      severity: page
    annotations:
      summary: Primary SAP-HANA resource down

  - alert: sap-hana-secondary-resource-absent
    expr: absent(cluster_node_resources{resource_name="rsc_saphana_prd_hdb00",role="slave",status="active"})
    labels:
      severity: page
    annotations:
      summary: there is no secondary SAP-HANA resource

- name: cluster-resources-monitoring
  rules:
  - alert: cluster-resources-a-resource-failed
    expr: count(cluster_node_resources{status="failed"}) > 0
    labels:
      severity: page
    annotations:
      summary: a cluster resource failed

- name: systemd-services-monitoring
  rules:
  - alert: service-down-pacemaker
    expr: node_systemd_unit_state{name="pacemaker.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: pacemaker service not running

  - alert: service-down-corosync
    expr: node_systemd_unit_state{name="pacemaker.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: corosync service not running

  - alert: service-down-sbd
    expr: node_systemd_unit_state{name="sbd.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: sbd service not running

  - alert: service-down-hawk
    expr: node_systemd_unit_state{name="hawk.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: hawk service not running

  - alert: service-down-hawk-backend
    expr: node_systemd_unit_state{name="hawk-backend.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: hawk-backend service not running

  - alert: service-down-node-exporter
    expr: node_systemd_unit_state{name="prometheus-node_exporter.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: ha-cluster-exporter service not running

  - alert: service-down-ha-cluster-exporter
    expr: node_systemd_unit_state{name="prometheus-ha_cluster_exporter.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: ha cluster exporter service not running
 
  - alert: service-down-hanadb-exporter
    expr: node_systemd_unit_state{name="hanadb_exporter@prd_00.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: hanadb exporter service not running
