groups:
# sap alerts
- name: sap-hana-resource-monitoring
  rules:
  - alert: sap-hana-master-resource-down
    expr: absent(ha_cluster_pacemaker_resources{id=~"rsc_saphana_.*",role="master"})
    labels:
      severity: page
    annotations:
      summary: Primary SAP-HANA resource down

  - alert: sap-hana-secondary-resource-absent
    expr: absent(ha_cluster_pacemaker_resources{id=~"rsc_saphana_.*",role="slave",status="active"})
    labels:
      severity: page
    annotations:
      summary: Slave SAP-HANA resource absent

# ha cluster alerts
- name: cluster-resources-monitoring
  rules:
  - alert: cluster-resources-a-resource-failed
    expr: count(ha_cluster_pacemaker_resources{status="failed"}) > 0
    labels:
      severity: page
    annotations:
      summary: A cluster resource failed

# sbd alerts

- name: sbd-device-alerts
  rules:
  - alert: a-sbd-device-unhealthy
    expr: ha_cluster_sbd_device_status == 0
    labels:
      severity: page
    annotations:
      summary: An SBD device in the HA cluster is unhealthy

# systemd services alerts
- name: systemd-services-monitoring
  rules:
  - alert: service-down-pacemaker
    expr: node_systemd_unit_state{name="pacemaker.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: Pacemaker service not running

  - alert: service-down-corosync
    expr: node_systemd_unit_state{name="pacemaker.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: Corosync service not running

  - alert: service-down-sbd
    expr: node_systemd_unit_state{name="sbd.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: SBD service not running

  - alert: service-down-hawk
    expr: node_systemd_unit_state{name="hawk.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: Hawk service not running

  - alert: service-down-hawk-backend
    expr: node_systemd_unit_state{name="hawk-backend.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: Hawk backend service not running

  - alert: service-down-node-exporter
    expr: node_systemd_unit_state{name="prometheus-node_exporter.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: Node exporter service not running

  - alert: service-down-ha-cluster-exporter
    expr: node_systemd_unit_state{name="prometheus-ha_cluster_exporter.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: HA Cluster Exporter service not running

  - alert: service-down-hanadb-exporter
    expr: node_systemd_unit_state{name=~"hanadb_exporter@.*.service", state="active"} == 0
    labels:
      severity: page
    annotations:
      summary: HANA exporter service not running

  - alert: node-filesystem-space-low
    expr: ((node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100) > 85
    labels:
      severity: page
    annotations:
      summary: Node filesystem space usage is higher than 85%

  - alert: stonith-disabled
    expr: ha_cluster_pacemaker_stonith_enabled == 0
    labels:
      severity: page
    annotations:
      summary: STONITH is disabled! Clusters without a fencing mechanism are not supported and have increased risk of data loss.
