groups:
- name: primary-resource-saphana-down
  rules:
  - alert: SAPHANAMasterResourcesDown
    expr: absent(cluster_node_resources{resource_name="rsc_saphana_prd_hdb00",role="master"})
    labels:
      severity: page
    annotations:
      summary: Primary SAP-HANA resource down

- name: a-resource-failed
  rules:
  - alert: aResourceFailed
    expr: cluster_node_resources{status="failed"} > 1
    labels:
      severity: page
    annotations:
      summary: a cluster resource failed

  
- name: secondary-resource-saphana-slave-role-changed
  rules:
  - alert: SAPHANAMasterResourcesDown
    expr: absent(cluster_node_resources{node="dma-dog-hana02",resource_name="rsc_saphana_prd_hdb00",role="slave"})
    labels:
      severity: page
    annotations:
      summary: secondary SAP-HANA resource role slave changed
