groups:
- name: primary-resource-saphana-down
  rules:
  - alert: SAPHANAMasterResourcesDown
    expr: absent(cluster_node_resources{resource_name="rsc_saphana_prd_hdb00",role="master"})
    labels:
      severity: page
    annotations:
      summary: Primary SAP-HANA resource down
