# github-actions workflow
# this test will just run terraform without salt
name: e2e tests

on: [pull_request]

jobs:
  terraform-sap-deployment:
    runs-on: self-hosted 

    steps:
    - uses: actions/checkout@v2
       
    - name: terraform apply
      run:  /tmp/terraform-apply.sh

    - name: some stuff
      run:  uptime

    - name: terraform destroy
      if: ${{ always() }}
      run:  /tmp/terraform-destroy.sh
